"""
WARNING: DO NOT USE THIS SCRIPT.
It was created as a bypass but it overwrites the beautiful 6-column 
Saliency/GradCAM grids generated by `fig_robust_model_failures.py` with 
barebones 2-column versions. To regenerate grids, always use 
`fig_robust_model_failures.py` directly.
"""
import os
import glob
import re
from PIL import Image

def create_grid(model_name, attack_status):
    """
    Stitches individual images from the robust_failures folder into a grid.
    Layout per row (one image pair): [Clean Image] | [Adversarial Image]
    Returns a PIL Image object.
    """
    folder = "robust_failures"
    # Find all clean images for this model and status
    # E.g., model_name="Liu2023_ConvNeXt-L", attack_status="fail"
    # Files look like: Liu2023_ConvNeXt-L_fail_1_class_696_clean.png
    
    clean_files = sorted(glob.glob(f"{folder}/{model_name}_{attack_status}_*_clean.png"))
    if not clean_files:
        print(f"No files found for {model_name} {attack_status}")
        return None

    # We expect 5 rows
    num_rows = min(len(clean_files), 5)
    
    # Open the first one to get the size
    sample_img = Image.open(clean_files[0])
    w, h = sample_img.size
    
    # We will lay them out in 2 columns: Clean, Adv
    # Saliency and CAM are missing from raw, so we skip them for a simple 2-col visual
    cols = 2
    grid_w = w * cols
    grid_h = h * num_rows
    
    grid_img = Image.new('RGB', (grid_w, grid_h), color=(255,255,255))
    
    for r in range(num_rows):
        clean_path = clean_files[r]
        # Infer the adv path
        adv_path = clean_path.replace("_clean.png", "_adv.png")
        
        if not os.path.exists(adv_path):
            continue
            
        img_clean = Image.open(clean_path)
        img_adv = Image.open(adv_path)
        
        # Paste Clean
        grid_img.paste(img_clean, (0, r * h))
        # Paste Adv
        grid_img.paste(img_adv, (w, r * h))

    return grid_img

def main():
    models = ["Liu2023_ConvNeXt-L", "Xu2024_Swin-L"]
    statuses = ["success", "fail"]
    
    for model in models:
        for status in statuses:
            grid = create_grid(model, status)
            if grid:
                output_name = f"fig_robust_failures_{model.split('_')[-1]}_{status}.png"
                grid.save(output_name)
                print(f"Generated {output_name}")

if __name__ == "__main__":
    main()
